Update CODEOWNERS
camaraproject/ReleaseManagement pull request #24
Opened 2024-04-29 17:32 UTC by hdamker

#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:

Adding @tanjadegroot as codeowner instead of Maroune.

#### Which issue(s) this PR fixes:

Fixes #23

2024-04-29 17:34 UTC, soadeyemo requested changes
Can you also remove @mar1bal  as he is no longer working with RelM WG? Thanks

2024-04-29 17:44 UTC, hdamker commented
> Can you also remove @mar1bal as he is no longer working with RelM WG? Thanks

From CODEOWNERS I have removed him, now also from MAINTAINER.md. He is still listed as reviewer due to the fact that he is in the current CODEOWNER file im `main`.

2024-05-12 13:57 UTC, hdamker commented
@soadeyemo Please approve and merge the PR

@soadeyemo @tanjadegroot and please accept the invitation to the camaraproject GitHub organization so that you get team members of the new teams @camaraproject/release-management_maintainers and @camaraproject/release-management_codeowners (which we are using to maintain the access rights within the repository).

2024-05-12 17:52 UTC, soadeyemo approved these changes

2024-05-12 17:53 UTC, merged