Add API-Readiness-Checklist.md to RM project
camaraproject/ReleaseManagement pull request #29
Opened 2024-05-15 12:34 UTC by tanjadegroot

#### What type of PR is this? 

* documentation

#### What this PR does / why we need it:

This file replaces the file in Commonalities and is updated as defined in the API release process in the Release Management Wiki Wiki (see https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist).

#### Which issue(s) this PR fixes:

Fixes #28 

#### Special notes for reviewers:

#### Changelog input

```
 Creation of updated API readiness checklist, removed from Commonalities

```

#### Additional documentation

2024-05-15 13:07 UTC, hdamker commented on documentation/API-Readiness-Checklist.md
> +|    |                                              |       |                   | initial | stable |
a) I suggest to add a column where APIs can add their status or how it is intended to use the table?
b) Two lines in the header seem not to work in GitHub MarkDown, the following suggestion might work but I have not tested it.

```suggestion
| Nr | API release assets                           | alpha | release-candidate |  public-release<br>initial | public-release<br> | Status for <api-name> <version> in rX.Y |
```

2024-05-15 13:08 UTC, hdamker commented on documentation/API-Readiness-Checklist.md
> +|    |                                              |       |                   | initial | stable |
api-name, version and release can also go in a section before the table.

2024-05-15 13:14 UTC, hdamker commented on documentation/API-Readiness-Checklist.md
> +# API Readiness Checklist
```suggestion
# API Readiness Checklist

Please find explanations for the criteria in the following checklist within [API Release Process](https://wiki.camaraproject.org/x/AgAVAQ#APIReleaseProcess-APIreadinesschecklist)
```

2024-05-15 13:15 UTC, hdamker commented on documentation/API-Readiness-Checklist.md
> +# API Readiness Checklist
Could alternatively also go below the table.

2024-05-15 17:36 UTC, hdamker commented on documentation/API-Readiness-Checklist.md
> +| 12 | Previous public-release was certified        |   O   |         O         |    O    |    M   |
Adding the missing column and center the others:
```suggestion
|----|----------------------------------------------|:-----:|:-----------------:|:-------:|:------:|---------------------|
|  1 | API definition                               |   M   |         M         |    M    |    M   |                     |
|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |                     |
|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |                     |
|  4 | API versioning convention applied            |   M   |         M         |    M    |    M   |                     |
|  5 | API documentation                            |   M   |         M         |    M    |    M   |                     |
|  6 | User stories                                 |   O   |         O         |    O    |    M   |                     |
|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |                     |
|  8 | Enhanced API test cases & documentation      |   O   |         O         |    O    |    M   |                     |
|  9 | Test result statement                        |   O   |         O         |    O    |    M   |                     |
| 10 | API release numbering convention applied     |   M   |         M         |    M    |    M   |                     |
| 11 | Change log updated                           |   M   |         M         |    M    |    M   |                     |
| 12 | Previous public-release was certified        |   O   |         O         |    O    |    M   |                     |
```

2024-05-16 10:11 UTC, hdamker approved these changes
LGTM - Thanks @tanjadegroot is shows for me what we have agreed within Release Management group. 

As this Checklist is very important for all Sub Projects I will ask today in the TSC meeting to review the PR and the linked document. So would be good to keep the PR open for about a week.

2024-05-16 10:50 UTC, bigludo7 approved these changes
Not a blocker, but, as we can understood the 4 columns as 4 steps should we add a note explaining that it is 'normal' to have initial public-release with same value than release candidate?

2024-05-31 14:51 UTC, FabrizioMoggio requested changes
Is it possible to put a link to the related documentation in the Comments column. This would improve the table also providing an overall a guide to the API development

2024-06-04 14:35 UTC, hdamker approved these changes

2024-06-04 15:02 UTC, jlurien commented on documentation/API-Readiness-Checklist.md
> +| 12 | Previous public-release was certified        |   O   |         O         |    O    |    M   |      |      |
If enhanced test plan is not required for the initial public release, and certification of the initial public release is required to have a stable public-release, this is assuming that the test plan used for the first certification is just the basic one, not the enhanced one, is this right? Or is that the initial public release has to be certified once the complete test plan is available.

2024-06-06 12:10 UTC, rartych commented
> Is it possible to put a link to the related documentation in the Comments column. This would improve the table also providing an overall a guide to the API development. Maybe we could first approve the table and then improve it with this links

@tanjadegroot  I think Fabrizio wanted to add links to guidelines/templates of specific assets, but providing the links to artifacts related to given API version is good idea for me.
@FabrizioMoggio The related documentation for different assets is linked in the Explanations table in the Wiki: https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist

2024-06-06 12:20 UTC, rartych approved these changes
LGTM

2024-06-06 13:20 UTC, tanjadegroot commented
> > Is it possible to put a link to the related documentation in the Comments column. This would improve the table also providing an overall a guide to the API development. Maybe we could first approve the table and then improve it with this links
> 
> @tanjadegroot I think Fabrizio wanted to add links to guidelines/templates of specific assets, but providing the links to artifacts related to given API version is good idea for me. @FabrizioMoggio The related documentation for different assets is linked in the Explanations table in the Wiki: https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist

The link is already there in the last line of the file

2024-06-06 13:38 UTC, tanjadegroot commented
@soadeyemo Hi Samuel, can you please review and approve the PR ?

2024-06-06 14:01 UTC, soadeyemo submitted a review, later dismissed
Reviewed and Approved.

2024-06-06 19:35 UTC, tanjadegroot commented
@soadeyemo - Hi Samuel, sorry,  but can you review and approve again please, I fixed some typos and explanations in the checklist.

2024-06-11 12:46 UTC, soadeyemo approved these changes
Reviewed and approved.

2024-06-11 12:46 UTC, merged